# Generated by Django 4.0.3 on 2022-04-15 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues_manager', '0004_remove_issue_project_id_issue_project_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issue',
            old_name='Project_id',
            new_name='project_id',
        ),
    ]
